# Generated by Django 4.2.5 on 2024-04-08 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField(unique=True, verbose_name='Id')),
                ('author', models.CharField(max_length=15, verbose_name='Автор')),
                ('rating', models.IntegerField(default=0, verbose_name='Репутация')),
                ('MP_author', models.BooleanField(default=False, verbose_name='Наиболее популярный')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, unique=True, verbose_name='Жанр')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления записи')),
            ],
            options={
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, unique=True, verbose_name='Ip адресс')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления записи')),
            ],
            options={
                'verbose_name_plural': 'Ip',
            },
        ),
        migrations.CreateModel(
            name='Tegs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teg', models.CharField(max_length=15, unique=True, verbose_name='Название тега')),
                ('creator', models.CharField(max_length=15, unique=True, verbose_name='Создатель тега')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления записи')),
            ],
            options={
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Musics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('file', models.CharField(max_length=100, verbose_name='Название музыкального файла')),
                ('img', models.ImageField(blank=True, default='main/img/music_1.jpg', null=True, upload_to='./musics files/music img', verbose_name='Изображение')),
                ('author', models.CharField(default='неизвестен', max_length=100, verbose_name='Автор')),
                ('text', models.TextField(blank=True, default='Ещё ни кто не добавил слова песни', null=True, verbose_name='Слова песни')),
                ('duration', models.CharField(max_length=7, verbose_name='Длительность')),
                ('rating', models.IntegerField(default=0, verbose_name='Репутация')),
                ('auditions', models.IntegerField(default=0, verbose_name='Количество прослушиваний')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('genres', models.ManyToManyField(blank=True, to='main.genres', verbose_name='жанры')),
                ('tegs', models.ManyToManyField(blank=True, to='main.tegs', verbose_name='Теги')),
            ],
            options={
                'verbose_name_plural': 'Музыка',
            },
        ),
        migrations.CreateModel(
            name='Ip_and_Musics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attitude', models.BooleanField(blank=True, null=True, verbose_name='Отношение')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления записи')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ip', verbose_name='Ip адресс который прослушал музыку')),
                ('music_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.musics', verbose_name='Id прослушанной музыки')),
            ],
            options={
                'verbose_name_plural': 'Прослушивания',
            },
        ),
    ]
